### ISSUE TITLE
Extract js-fundamentals sections into their own exercise repositories

### ISSUE THREAD

**Issue by vherus** [boolean-uk/software-developer#123]
Each subject in https://github.com/boolean-uk/js-fundamentals needs to be moved to its own repo with the following requirements:

- [ ] `js-fundamentals-[topic]` repo naming
- [ ] Focused on a single subject (Arrays, Objects, Strings, Variables, etc.)
- [ ] More content added as extensions
- [ ] Core criteria reviewed and improved where necessary
- [ ] Learning objectives added
- [ ] Clear instructions on running tests
- [ ] Husky, lint & CI configured
- [ ] Added to Montessori
- [ ] Sequence updated to point to the individual exercises

To be done prior to Cohort 8 starting

**Comment by shahzadnaeem** [comment]
Happy to take this on over the Summer Break

This should not take too long as it is splitting existing code and adding instructions

**Comment by shahzadnaeem** [comment]
Tasks for Ed to complete

- [ ] Learning objectives
- [ ] Adding to Montessori

- Create some examples of additional things like extensions for review
- Ensure all hooks etc are tested
-

**Comment by shahzadnaeem** [comment]
- Renamed js-fundamentals-functions-3 to js-fundamentals-functions
- Renamed js-fundamentals-functions-2 to zz__js-fundamentals-functions-2
- Starting work on js-functions-fundamentals

**Comment by shahzadnaeem** [comment]
Have updated/created all required js-fundamentals-XXX exercises from js-fundamentals

Will review tomorrow to look at extensions for the exercises and adding thinking about what can be added in each case.

**Comment by shahzadnaeem** [comment]
Added extension exercise to the following:
- Arrays
- Variables (possibly better in Data Types)
