### ISSUE TITLE
Add morning exercise solutions to programming-fundamentals content

### ISSUE THREAD

**Issue by vherus** [boolean-uk/software-developer#126]
In the sequence items for JS fundamentals, each day has a morning exercise in code snippet blocks. These need some solutions for the morning teachers.

**Comment by shahzadnaeem** [comment]
Solutions addded to  new https://github.com/boolean-uk/js-fundamentals-teachers-notes repo that contains all code and solutions for all js-fundamentals sequence items

**Comment by shahzadnaeem** [comment]
TODO: Remove existing content from Notion once reviewed

**Comment by vherus** [comment]
@shahzadnaeem thanks for this.

Let's make a few changes to this one:

1. Rename the repo to `js-fundamentals-morning-sessions`
2. Remove the `full-exercise-exemplar` directory and add publicly visible exemplar repositories for each of the newly extracted fundamentals repos  (e.g. `js-fundamentals-objects-exemplar`)
3. Update the Sequence Items links in the readme to point to the relevant sequence items in Notion
