### ISSUE TITLE
Review new per subject area js-fundamentals repos

### ISSUE THREAD

**Issue by shahzadnaeem** [boolean-uk/software-developer#133]
The following new repos need to be reviewed for correctness - see also #123 

- https://github.com/boolean-uk/js-fundamentals-functions-1
- https://github.com/boolean-uk/js-exercise-template
  - Includes support for multiple core and extensions files/tests plus an 'all'
- https://github.com/boolean-uk/js-fundamentals-primitive-data-types
- https://github.com/boolean-uk/js-fundamentals-variables
- https://github.com/boolean-uk/js-fundamentals-loops
- https://github.com/boolean-uk/js-fundamentals-conditional-flow
- https://github.com/boolean-uk/js-fundamentals-arrays
- https://github.com/boolean-uk/js-fundamentals-objects
- https://github.com/boolean-uk/js-fundamentals-functions-2 - NPM update
- https://github.com/boolean-uk/js-fundamentals-functions-3 - NPM update

Check for the following:

- [ ] Learning objectives are correct
- [ ] Extensions - Have two Jasmine configs now, one for core and one for extensions
  - Review and decide what extensions are required. Also update main README.md
- [ ] Have been added to Montessori
- [ ] Sequence links updated in Notion
- [ ] ESLint setup requirements for VSCode
- [ ] Relvant MDN links present?
- [ ] Others???

In addition Husky operation needs to be checked. Maybe specific to Linux where I'm seeing it? Permission change in README, or change locally and commit. Looks like `git update-index --chmod=+x <file>` can do this...
Getting the following warning when pushing:

```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```

**Comment by shahzadnaeem** [comment]
Formatting of exercises needs to be reviewed also. The `package.json` file includes packages that automate the formatting of code and tests using the defined ESLint rule which include the use of Prettier. This is defined in the Environment Setup Guide, but I can't find details of the VSCode settings that are required to enable the automatic use of ESLint as a formatter.

- In VSCode Settings
  - Type `formatt` in 'Search Settings' and update the following
    - `Text Editor/Formatting` - Enable Format On Paste and Format On Save
    - `Extensions/ESLint` - Enable ESLint as a formatter
    - `Extensions/Typescript` - Disable BOTH Javascript and Typescript formatters

All exercises should be formatter using the above settings so as to avoid the 'sea of red squiggles` which is very distracting to students - especially the new ones.

**Comment by vherus** [comment]
Thanks for your work on this @shahzadnaeem - I think we can go ahead and remove the todo's about extensions and I'll do a once over to add LO's. If there are any with missing descriptions (In this exercise you will...), let's just get rid of those for now.

I'll create a separate issue for adding extensions to these repos, it's not a priority.

RE The template repo you created, there's already an existing JS template repo here: https://github.com/boolean-uk/js-template-repo

Let's stick with using that original one - could you move the work you did in your template repo to there and delete the new one? You likely made some improvements we should introduce to the original

**Comment by shahzadnaeem** [comment]
Updates following review comments from Nathan

- js-template repo updated and js-exercise-template deprecated
-
