### ISSUE TITLE
Move away from Heroku

### ISSUE THREAD

**Issue by vherus** [boolean-uk/software-developer#143]
> Starting November 28th, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available.

For action by November 1st

Dashboard login details available pinned in team dev admin channel.

- Which platform to switch to
- Impact on exercises
- New deploy process documentation
- GitHub actions

**Comment by vherus** [comment]
@dearshrewdwit Investigate AWS solutions by 23rd October

**Comment by vherus** [comment]
Action: Redeploy the rest of our apps with fly.io by end of 04/11 @dearshrewdwit

**Comment by dearshrewdwit** [comment]
Nothing else is critical - this is now done.
