### ISSUE TITLE
Upgrade all NodeJS projects to current LTS

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#151]

**Comment by vherus** [comment]
@dearshrewdwit test an exercise from fundamentals
@vherus test an exercise from backend module
Someone to test an exercise from React module

**Comment by dearshrewdwit** [comment]
Update see: https://discord.com/channels/811981269595324436/943891385696792657/1040295869695664168 for more info


![Screenshot 2022-11-10 at 16 29 11](https://user-images.githubusercontent.com/13719921/201152095-5156744d-0fed-4968-990c-bd9e42882376.png)

**Comment by dearshrewdwit** [comment]
It looks like this should work fine so far for simple nodejs projects (i've also separated out the standard/extension workflows)

**Comment by vherus** [comment]
For my own ref: https://github.com/boolean-uk/js-fundamentals-primitive-data-types/blob/main/.github/workflows/standard-criteria-tests.yml

**Comment by dearshrewdwit** [comment]
No current problems
- used NodeJS LTS: v18.12.1
- installed dependencies and ran an existing exercise: https://github.com/boolean-uk/react-greengrocers

Next, will use the tool create-react-app

**Comment by dearshrewdwit** [comment]
No issues using create-react-app with NodeJS LTS: v18.12.1

**Comment by vherus** [comment]
Investigate a bot to see if we can automate upgrading the node dep to latest LTS for exercises

**Comment by chris2733** [comment]
Checking which repos are correct:
[Fundamentsl ](https://github.com/boolean-uk/js-fundamentals-control-flow)
https://github.com/boolean-uk/js-fundamentals-objects

Pull requests on these:
https://github.com/boolean-uk/js-fundamentals-variables/pull/22

**Comment by dearshrewdwit** [comment]
Let's bump up the priority on this so that tomorrow these repos are all resolved.

Repos needing workflows:
[Fundamentals arrays](https://github.com/boolean-uk/js-fundamentals-arrays)
[Fundamentals functions 3](https://github.com/boolean-uk/js-fundamentals-functions-3)

Pull requests on these:
https://github.com/boolean-uk/js-fundamentals-variables/pull/22
