### ISSUE TITLE
Template Repos

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#165]
Task
https://github.com/boolean-uk/team-dev-server-template
- update the OpenAPI yml to match current behaviour
- Use redoc cli to create the html view -> in the docs dir
- set up GH pages to server from docs dir

**Comment by vherus** [comment]
This is taking a bit longer than anticipated, there are a lot of inconsistencies in the API spec

**Comment by vherus** [comment]
User, post, cohort and log are done and consistent now. The YAML isn't pretty.

What's left:

- note
- conversation
- exercise
- comment

Responses should follow the structure:

```json
{
  "status": "string",
  "data": {
    "property1": "type",
    ...
  }
}
```

See the existing responses for the ones I've cleaned up as a reference for how to include nested entities.

Some of the endpoints may not make sense on those left to complete, please make sure they make sense.

E.g. "Create cohort exercise":
Currently: `/exercises/{id}/cohortExercises`

That route can be removed with an optional `cohortId` property added to the "Create exercise" route's request body

**Comment by vherus** [comment]
- Continue with the archived changes, bring the spec to a smaller & consistent state
- Implement the client changes RE #166 to that spec

**Comment by vherus** [comment]
- Complete archived work, stripping out endpoints from spec
