### ISSUE TITLE
Reimplement FE TDS repo(s) following design

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#166]
See #141

**Comment by vherus** [comment]
Next team dev sim starts Jan 30th @vherus

**Comment by vherus** [comment]
- Ensure API interactions match the updated backend API spec
- Refactor allowed :)

**Comment by vherus** [comment]
- Fork https://github.com/boolean-uk/team-dev-client into `team-dev-client`
- Reset to the last sensible teacher commit
- Review before build: is it worth start a new react app or refactoring what's there?

**Comment by vherus** [comment]
https://www.npmjs.com/package/sweetalert2
https://github.com/sweetalert2/sweetalert2-react-content
