### ISSUE TITLE
Database ORM test suite

### ISSUE THREAD

**Issue by vherus** [boolean-uk/software-developer#168]
Investigate if there's a built-in way to test schema files for https://github.com/boolean-uk/database-orm-1

Alternatively, test suite that tests seed functions

**Comment by vherus** [comment]
Prisma has a guide for mocking the client specifically for unit testing: https://www.prisma.io/docs/guides/testing/unit-testing

**Comment by dearshrewdwit** [comment]
What, spinning up db servers within a GitHub action for every exercise every single time a a cohort full of students pushes work isn't cool?

**Comment by julesnuggy** [comment]
I went through the Prisma guide on Unit Testing and it is not suitable for what we want (testing the schema) or for our project setup (JS and not TS). The various issues are:
1. The `jest-mock-extended` library does not work as intended (i.e. to mock the prisma client and its functions). It fails to even read the prisma models, so `prisma.customer.create` will throw an error because it is `undefined` despite having setup the mock prisma client.
2. This library is intended for TS projects, and whilst it could in theory be made to work by having TS files only for the test suite, the unit testing that Prisma outline are for unit testing DB query functions (e.g. `createCustomer`), as opposed to the schema itself. So the only "model checking" is via the TS types/interfaces that we would create purely for the tests!

I think the only way to test the schema would be to implement Integration Testing: https://www.prisma.io/docs/guides/testing/integration-testing#prerequisites

**Comment by julesnuggy** [comment]
We spoke briefly about using Jasmine to test that the Prisma Client is able to generate the models/data, but if that's all we need to do then surely we could just stick with pure Jest?


![Image](https://user-images.githubusercontent.com/16806557/217215100-4c3d9327-476d-4215-b2e2-983eb59906cf.png)

**Comment by vherus** [comment]
I personally prefer Jest so have no problem with using it but the rest of the exercises use Jasmine so it may add confusion for students when they suddenly have a different test command to run

**Comment by julesnuggy** [comment]
Ah OK, then I think consistency for the students will be more important in this case!

**Comment by dearshrewdwit** [comment]
```

Important: You need to re-run the prisma generate command after every change that's made to your Prisma schema to update the generated Prisma Client code.

...

Note also that prisma generate is automatically invoked when you're installing the @prisma/client npm package. So, when you're initially setting up Prisma Client, you can typically save the third step from the list above.
```

This sounds like in the GitHub action it will be fine - because it will install the project from scratch.

If students run the test locally, we'll have to simply include the command  `npx prisma generate` before running the tests

eg: `npx prisma generate && npx jest`

**Comment by dearshrewdwit** [comment]
> I personally prefer Jest so have no problem with using it but the rest of the exercises use Jasmine so it may add confusion for students when they suddenly have a different test command to run

The APIs & Datastores module uses jest as the test runner for exercises and challenges - so I recommend using it.

You might be thinking of Dev Approaches?

**Comment by dearshrewdwit** [comment]
might even be simpler to do something like this using `ts-jest` - create some objects that obey the model's type in each test

```ts
import type { Customer, User } from '@prisma/client'; // we would have to declare the model names here and keep them hardcoded, as with the model properties

describe('test', () => {
  it('Customer model', async () => {
    const customer: Customer = {
      id: 1,
      name: 'Ed',
      createdAt: new Date(),
      updatedAt: new Date()

    }
  })

  it('User model', async () => {
    const user: User = {
      id: 1,
      name: 'Ed',
      age: 100,
      createdAt: new Date(),
      updatedAt: new Date()
    }
  })
})

```

Where the test script is `"npx prisma generate && npx jest"`

**Comment by dearshrewdwit** [comment]
Not sure how feasible this would be to test constraints/validations - but could be explored maybe

Model relationships should be testable with this approach

**Comment by dearshrewdwit** [comment]
Great investigations @julesnuggy @vherus - i think we're on the right lines here

**Comment by julesnuggy** [comment]
So, I wanted to try and avoid adding TypeScript to the repo just for the sake of testing, and I've found a way! 

The `prisma` client instance contains an object which holds all of the data on the models: `prisma._dmff.modelMap.<MyModelName>`.

So, given a model like this:
```js
model User {
  id          Int      @id @default(autoincrement())
  email       String
  password    String  @db.VarChar(255)
  isActive    Boolean @default(true)
  customerId  Int
  customer    Customer  @relation(fields: [customerId], references: [id])
}
```

If we inspect `prisma._dmmf.modelMap.User.fields`, then we get back:

```js
[
  {
    name: 'id',
    kind: 'scalar',
    isList: false,
    isRequired: true,
    isUnique: false,
    isId: true,
    isReadOnly: false,
    type: 'Int',
    hasDefaultValue: true,
    default: { name: 'autoincrement', args: [] },
    isGenerated: false,
    isUpdatedAt: false
  },
  {
    name: 'email',
    kind: 'scalar',
    isList: false,
    isRequired: true,
    isUnique: false,
    isId: false,
    isReadOnly: false,
    type: 'String',
    hasDefaultValue: false,
    isGenerated: false,
    isUpdatedAt: false
  },
  {
    name: 'password',
    kind: 'scalar',
    isList: false,
    isRequired: true,
    isUnique: false,
    isId: false,
    isReadOnly: false,
    type: 'String',
    hasDefaultValue: false,
    isGenerated: false,
    isUpdatedAt: false
  },
  {
    name: 'isActive',
    kind: 'scalar',
    isList: false,
    isRequired: true,
    isUnique: false,
    isId: false,
    isReadOnly: false,
    type: 'Boolean',
    hasDefaultValue: true,
    default: true,
    isGenerated: false,
    isUpdatedAt: false
  },
  {
    name: 'customerId',
    kind: 'scalar',
    isList: false,
    isRequired: true,
    isUnique: true,
    isId: false,
    isReadOnly: true,
    type: 'Int',
    hasDefaultValue: false,
    isGenerated: false,
    isUpdatedAt: false
  },
  {
    name: 'customer',
    kind: 'object',
    isList: false,
    isRequired: true,
    isUnique: false,
    isId: false,
    isReadOnly: false,
    type: 'Customer',
    hasDefaultValue: false,
    relationName: 'CustomerToUser',
    relationFromFields: [ 'customerId' ],
    relationToFields: [ 'id' ],
    isGenerated: false,
    isUpdatedAt: false
  }
]
```

It's a shame that it doesn't show us the specific native type for `password` (_VARCHAR(255)_) but I think the `isRequired`, `default`, `relationTo/FromFields`  constraints are sufficient for writing some tests.

**Comment by dearshrewdwit** [comment]
That's great stuff  - the assertions will still be quite straightforward with the added benefit of being able to assert on constraints and relations too.

Can you create a PR to main with an example test suite?

**Comment by julesnuggy** [comment]
@dearshrewdwit @vherus -- PR is now finalised for review.

If  you want a schema which passes all tests, here is one:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}

model Customer {
  id        Int      @id @default(autoincrement())
  name      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  contact   Contact?
  tickets   Ticket[]
}

model Contact {
  id         Int      @id @default(autoincrement())
  customer   Customer @relation(fields: [customerId], references: [id])
  customerId Int
  phone      String
  email      String
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}


model Movie {
  id          Int   @id @default(autoincrement())
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  runtimeMins Int
  title       String
  screenings  Screening[]
}

model Screen {
  id            Int @id @default(autoincrement())
  number  Int
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
  screenings    Screening[]
}

model Screening {
  id          Int   @id @default(autoincrement())
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  startsAt    DateTime
  movie       Movie @relation(fields: [movieId], references: [id])
  movieId     Int
  screen      Screen @relation(fields: [screenId], references: [id])
  screenId    Int
  tickets     Ticket[]
}

model Ticket {
  id            Int   @id @default(autoincrement())
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
  customer      Customer @relation(fields: [customerId], references: [id])
  customerId    Int
  screening     Screening @relation(fields: [screeningId], references: [id])
  screeningId   Int
}
```

**Comment by julesnuggy** [comment]
The update to Prisdma 4.9.0 means this needs some adjusting 😑

**Comment by julesnuggy** [comment]
OK, now it's ready!

**Comment by julesnuggy** [comment]
@vherus @dearshrewdwit -- is this good to merge? 🙃 
https://github.com/boolean-uk/database-orm/pull/11

**Comment by dearshrewdwit** [comment]
Yes, let's get it done and ready for cohort 9
