### ISSUE TITLE
Student Request: A Boolean CodeWars Clan

### ISSUE THREAD

**Issue by vherus** [boolean-uk/software-developer#171]
Not sure what's involved but presumably it's a community that can be set up on CodeWars. A few C8 students requested it, might be a fun addition.

- Investigate what it is, what's involved in setting it up / running it, benefits / drawbacks

**Comment by vherus** [comment]
Use teaching@boolean.co.uk to set up

**Comment by dearshrewdwit** [comment]
A short investigation reveals the only needed data to set up a 'clan' is a string of a certain value. When others also use the same string accounts can see and compare results.

Log in, go to account settings top right.
![Image](https://user-images.githubusercontent.com/13719921/211772347-3ab374aa-22cb-4c48-9f8d-9617690598e5.png)

Update account with clan name: 'Boolean UK'
![Image](https://user-images.githubusercontent.com/13719921/211771992-1a707064-3dba-493f-a488-815d71b21f14.png)

**Comment by dearshrewdwit** [comment]
Next Step

- verify with teachers.
@vherus @dogezen @julesnuggy @Auenc @Logi13 @chris2733 Please create/update account settings accordingly

**Comment by vherus** [comment]
Todo: Tell students
