### ISSUE TITLE
TDS improvements

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#179]
Add items of work that will improve

- teacher setup
- teacher documentation
- student setup 
- student documentation
- change review process
- etc

**Comment by vherus** [comment]
- Create a handbook to give out to students with all of the info they need (e.g. how to branch, merge, rules for PRs etc)

**Comment by dearshrewdwit** [comment]
Started here: https://www.notion.so/boolean/Team-Development-Simulation-Students-215c52e827af4fc9bde635af52dcc25d

Contribute when you can @dogezen @vherus

**Comment by julesnuggy** [comment]
Guide V1.0 is ready. Thanks to Nathan, Carlo and John for their reviews. Additional feedback welcome / feel free to modify.
https://www.notion.so/boolean/Team-Development-Simulation-Students-Handbook-215c52e827af4fc9bde635af52dcc25d

**Comment by dearshrewdwit** [comment]
Great! I'll close this ticket - when the next delivery happens there might be on occasion to review and update.
