### ISSUE TITLE
Peer Groups

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#18]
Divide the cohort into small groups of 3-5. Change groups each module.

Daily, at 2pm, peer groups meet to discuss the following 4 things:
- key takeaways from the morning
- current learning blockers
- intentions for the afternoon
- other thoughts and suggestions

Peer groups post into their cohort channel the aggregated info^

2:20pm - afternoon teachers and cohort go on zoom and spend up to 10 minutes reading through the shared summarues, answering any questions or organising optional breakout sessions for those interested.

Expected outcomes
- student accountability for being back online ready for the afternoon at 2pm
- shared visibility on student progress/thoughts from standup summaries
- small group promotes bonding/safe learning space
- if the peer groups don't change much, they can become an organisational tool for workshops or other sessions

requirements
- create discord channels for each peer group to chat
- morning teacher facilitates for the first week?

**Comment by vherus** [comment]
This sounds great! Question about this bit: `Change groups each module.`

In doing research into team based learning the general consensus I've seen is that educators try not to change groups once they're created, just wondering what the pros and cons are of doing this

**Comment by glowkeeper** [comment]
Sounds great and will help reinforce learnings. But re: _morning teacher facilitates_ - I am unavailable at 2 pm on Mondays and Fridays :(

**Comment by dearshrewdwit** [comment]
> This sounds great! Question about this bit: `Change groups each module.`
> 
> In doing research into team based learning the general consensus I've seen is that educators try not to change groups once they're created, just wondering what the pros and cons are of doing this

@vherus great question. Agreed. An important part of using a team/small group of students is the safe space it creates. If facilitated well they build trust with each other and it helps create a useful source of information.

The idea is that they can spend long enough to build this with each other and then rotate around the cohort, sothat they can build these relationships with others. This also mitigates risk where groups that have personality clashes.

I don't know if there's a magic number, but 4 weeks might be a good starting point to see how the relationships build. I'm open to 6weeks or longer. It feels like it should mirror a course sequence cadence.

What do you think?

**Comment by dearshrewdwit** [comment]
> Sounds great and will help reinforce learnings. But re: _morning teacher facilitates_ - I am unavailable at 2 pm on Mondays and Fridays :(

Good to know. I suspect this is this case in general, so I think for Cohort 5 onwards it should be only the afternoon teachers that facilitate this.

**Comment by dearshrewdwit** [comment]
@glowkeeper - would you be interested in starting this with Cohort 3?

**Comment by glowkeeper** [comment]
I'm keen yes - I think they're a tight group, and this would help reinforce
that.

**Comment by mikemherron** [comment]
I'm all for this for Cohort 4. I'll add it to their shared calendar, and also udpate the intro deck where we talk about the daily schedule.

**Comment by vherus** [comment]
> I don't know if there's a magic number, but 4 weeks might be a good starting point to see how the relationships build. I'm open to 6weeks or longer. It feels like it should mirror a course sequence cadence.
> 
> What do you think?

Thank you! 4 weeks seems like a good starting point to me as well. It'll give us chance to see how it goes before extending it

**Comment by dearshrewdwit** [comment]
Implemented starting with Cohorts 3, 4.
Documented in Notion:
> https://www.notion.so/boolean/Facilitate-Peer-Groups-a7cb935dee6847cab292a5417ed07589
