### ISSUE TITLE
Create Module: Programming Fundamentals

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#181]
## 1. Product
- [ ] Create course requirements doc
- [ ] Create new module and sequence
- [ ] Update views

## 2. Course Content

Demonstrate with 1 exercise
- https://github.com/boolean-uk/java-scrabble-challenge (add example implementations here)
- [x] implement
- [x] write tests
- [x] add github action
- [x] identify anchor skills

Translate or create the following exercises
- [x] Class, public/private
- [x] Variables &  Data Types
- [x] constructors, methods, overloading
- [x] arrays
- [x] if statements
- [x] loops

**Comment by vherus** [comment]
At what point do we think using multiple classes should come into it? We can likely do a lot of programming fundamentals just using the Main class, even the scrabble challenge really

**Comment by dearshrewdwit** [comment]
Let's, from the beginning, use Main as a runner which uses other classes from the same package - means the classes can be unit tested easily.

**Comment by vherus** [comment]
I've added a JUnit exercise setup using Gradle to the repo: https://github.com/boolean-uk/java-scrabble-challenge

@dearshrewdwit could you try cloning it and making sure it builds? There is no solution implemented but it should at least install the JUnit dependencies

![Image](https://user-images.githubusercontent.com/5518649/218717100-9839b5b6-f78b-41ab-894f-428fba037417.png)

**Comment by vherus** [comment]
Implemented an exemplar here: https://github.com/boolean-uk/java-scrabble-challenge-exemplar

**Comment by vherus** [comment]
Setting up some CI is going to be a challenge but I think that's the next step for the scrabble challenge repo

**Comment by vherus** [comment]
Anchor skills for scrabble challenge:

- Basic Git functionality
- Building & running a Java project using gradle
- Class / method visibility
- Encapsulation
- Class constructors
- Data types / return types
- Variable scope
- Loops
- String manipulation
- Collections & generic types (enough to type a Map, not to type custom functions)
- Arrays

**Comment by vherus** [comment]
There are 2 things in consideration for the rest of the fundamentals exercises so far:

1. Separate test suites for core criteria and extensions. There are a few different ways to do it, gradle test suites & gradle tasks seem to be the best candidates. Currently figuring out how to implement these

2. There are some exercises that come before functions are introduced so the js tests are expecting exported variables. How do we aproach these?
- Classes need to come before everything because it's Java
- Do we have the students create public members that we can test or do we teach methods and returning data types from the beginning? E.g.

Public member approach:

```js
const firstName = 'Jane'
const secondName = 'Smith'

// Set this variable to firstName and secondName concatenated
const fullName = null

module.exports = {
  a: fullName
}
```

becomes

```java
public class Strings {
  String firstName = "Jane";
  String lastName = "Smith";

  // Set this variable to firstName and secondName concatenated
  public String fullName = "";
}
```

**Comment by vherus** [comment]
Java exercise template repo with example PR here: https://github.com/boolean-uk/java-template

**Comment by dearshrewdwit** [comment]
Let's review on Monday. By then I'll create a provisional sequence we can pick apart that would make sense.

Classes and public fields right from the start makes sense to me. We can leave the access modifiers until we visit encapsulation deeper.
