### ISSUE TITLE
Create Module: APIs & Data Stores

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#183]

**Comment by vherus** [comment]
Current thoughts on the differences between current JS curriculum and Java version:

- Define the most commonly used Spring Boot annotations
- Break down any important builder classes, e.g. HTTP requests
- Trim the SQL exercises into a single day, no more than a single 1:n join
- Light touching on necessary design patterns, e.g. repository & builder
- Explanation of IOC containters & how Spring's works
- Exercise structure? Should we follow something standard like below?
```
com.booleanuk.apis.exercisename
+- Application.java
|
+- model1
|        +- Model1.java
|        +- Model1Controller.java
|        +- Model1Service.java
|        +- Model1Repository.java
|
+- model2
|        +- Model2.java
|        +- Model2Controller.java
|        +- Model2Service.java
|        +- Model2Repository.java
```

**Comment by vherus** [comment]
Before final project, lesson on setting up a spring project using initializr

**Comment by dearshrewdwit** [comment]
Two oustanding items of work.

1. Morning activity for MVC with Postgres (almost at the end of)  (2nd June)
2. Afternoon activity with the above.
3. Morning activity for MVC with Hibernate JPA (5/6th June)
