### ISSUE TITLE
Create tech test resource

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#19]
Currently the list:

https://github.com/Skyscanner/full-stack-recruitment-test
https://app.testdome.com/t/01f0a26a520f443cb827e22ff6b8caea
https://app.beapplied.com/application-feedback/6B3jd5Lw5pTk1vv76lVX6L/
https://github.com/catlirex/T9Phone 
https://app.codility.com/programmers/lessons/1-iterations/binary_gap/
https://docs.google.com/document/d/1mP0nI2n0tGAJkhGygXjcLtqha_qK5DZKap6OiEv1qRw/edit?usp=sharing
https://github.com/stu-dev/test-js-grad

**Comment by dearshrewdwit** [comment]
- Tech tests form part of the module challenges
- need example implementations

**Comment by Auenc** [comment]
The first two links appear to be dead (for me). First one says the invite has expired, and second one just opens to discord DMs despite refreshes

**Comment by dearshrewdwit** [comment]
> The first two links appear to be dead (for me). First one says the invite has expired, and second one just opens to discord DMs despite refreshes

Ah, that's frustrating for the first one. Second one resolved.

**Comment by dearshrewdwit** [comment]
Actions
- Create a github repository
- include guide how to approach tech tests
- include a tech test self-review guide
- Identify a point in the course to share with students
  - maybe include as part of module Tech Test Prep?

**Comment by dearshrewdwit** [comment]
[Junior_Developer_Coding_Test.pdf](https://github.com/boolean-uk/software-developer/files/8631551/Junior_Developer_Coding_Test.pdf)

**Comment by dearshrewdwit** [comment]
[Vonage_-_The_interview_problem.pdf](https://github.com/boolean-uk/software-developer/files/8670739/Vonage_-_The_interview_problem.pdf)

**Comment by dearshrewdwit** [comment]
[Junior_Fullstack_Engineer_-_Exercise.pdf](https://github.com/boolean-uk/software-developer/files/8754871/Junior_Fullstack_Engineer_-_Exercise.pdf)

**Comment by dearshrewdwit** [comment]
Convert to JS:

Ruby Developer Test

Before you start coding (and let’s be honest, we know that’s what you want to do), please read the following.

Firstly, the test should take you no more than 2.5 hours to complete.

Secondly, the test is for us to see how you code and the methodologies you use, what we will be looking for in this test are the following:

● Functionality

● Efficiency — We like clean, simple code.

● Readability

● Tests (we have 96% test coverage in our code and we aim to keep it that way).

● Also, we would like to understand your ability to use TDD and OO, so please ensure these are part of your complete test.

● Feel free to submit your solution as a link to your version control repository

The test is as follows:

1. ruby_app

Write a ruby script that:

a. Receives a log as argument (webserver.log is provided)

e.g.: ./parser.rb webserver.log

b. Returns the following:

> list of webpages with most page views ordered from most pages views to less page views

e.g.: /home 90 visits /index 80 visits etc… > list of webpages with most unique page views also ordered e.g.: /about/2 8 unique views

/index 5 unique views etc…

Finally, have some fun — Feel free to make changes or design something if you think it meets the criteria above, but would produce better outcomes and of course, the sooner you return the test, the quicker we can move the process.

If you want to code it up yourself, the test file is over here: https://textuploader.com/159t1

**Comment by dearshrewdwit** [comment]
[Golden_Shoe_.pdf](https://github.com/boolean-uk/software-developer/files/9052670/Golden_Shoe_.pdf)

**Comment by dearshrewdwit** [comment]
[Feature_Idea.docx](https://github.com/boolean-uk/software-developer/files/9052672/Feature_Idea.docx)

**Comment by dearshrewdwit** [comment]
https://gist.github.com/ractive/8ea5e93b26ab24e5caf58d1c8c235b0d

**Comment by dearshrewdwit** [comment]
https://github.com/PepperHQ/backend-challenge
