### ISSUE TITLE
Feedback on Delivery Log

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#22]
The delivery log for Cohort 4 is here

> https://www.notion.so/boolean/Delivery-Log-Cohort-4-10cd8fbc3ee448419f5b2c890e58594c#30c64377a8b4467984a1272c2325cb60

### Feedback
Imagine in a few months' time, starting a new cohort either as a morning or afternoon teacher. How could this delivery log be more useful to you to understand what you need to do to deliver the course?

Please leave your feedback as comments on this issue.

### Details
The log is for teachers to find out exactly what happened. Anything that we do is made explicit so it's not lost in our heads -it's there for everyone to see so that.

We'll use the log to improve the source of truth for the course delivery plan - what any teacher can use to delivery the course and know what to do each day.

The focus is on what reporting what content was delivered, how it was delivered and by whom, any adjustments made (or can be "according to plan").  Any changes to the plan we had to make should be documented - for example, more time on topics, less time on topics, technical problems, material problems etc. Anything specific that should be brought to the attention of the next instructor or taken in to consideration for future planning please **highlight in red.**

**Comment by dearshrewdwit** [comment]
@boolean-uk/staff there's a deadline of December 1st on this for initial feedback.

**Comment by vherus** [comment]
I think this log is amazing. It's already starting to look a little difficult to work with (it's very long with no immediately accessible way to get to the relevant day other than scrolling to the top and clicking an anchor link)

It might be useful to organise it into a table with a note page embedded in one of the columns. Check out the way I handled this with the project plans here: https://www.notion.so/boolean/10b1f4a697434f739c461f694462f09f?v=0cd33ade77dd41c28ce636d6e764fac3

Each row is a specific project, and there's an embedded page in the *"Plan"* column with the details. This is making it really easy to keep things manageable. It'll also open the door to filtering so you can easily find logs for a certain day.

**Comment by dearshrewdwit** [comment]
Thanks @vherus. Useful feedback. Agreed, a calendar view sounds like a good next step.
