### ISSUE TITLE
Create: TDD OOP inheritance

### ISSUE THREAD

**Issue by Logi13** [boolean-uk/software-developer#224]
- [x] exercise: https://github.com/boolean-uk/csharp-tdd-oop-inheritance
- [ ] Sequence: https://www.notion.so/boolean/C-TDD-OOP-inheritance-eb93cfaf7e24421fb2ac9a56d41af9de?pvs=4

**Comment by uerbzr** [comment]
https://github.com/boolean-uk/csharp-tdd-oop-inheritance-workshop
