### ISSUE TITLE
React Exercises GitHub Port - Yet another Survey w/ Reusable Components

### ISSUE THREAD

**Issue by glowkeeper** [boolean-uk/software-developer#34]

**Comment by stevenrico** [comment]
This was overly complex.

I made it smaller by just having one set of radios, checkboxes....

**Comment by glowkeeper** [comment]
I ported its sibling yesterday: https://github.com/boolean-uk/boolean-uk-react-survey - does that need simplifying, too?

**Comment by stevenrico** [comment]
No longer needed.
