### ISSUE TITLE
React Exercises GitHub Port - Brewery Tours

### ISSUE THREAD

**Issue by glowkeeper** [boolean-uk/software-developer#37]

**Comment by dearshrewdwit** [comment]
Notion: https://www.notion.so/boolean/Day-10-11-Brewery-Tours-React-3214534cb475472cb61c088c009335ab
codesandbox: https://codesandbox.io/s/brewery-tours-react-starter-template-zgtcp

For this one - when importing to github, codesandbox threw an exception saying github repo was empty. GitHub created the repo, but only with a default README. 

I manually copied across files.

GitHub: https://github.com/boolean-uk/boolean-uk-react-brewery-tours

**Comment by dearshrewdwit** [comment]
Moved gif across. Updated Notion
