### ISSUE TITLE
API Module: Create Delivery Plan

### ISSUE THREAD

**Issue by stevenrico** [boolean-uk/software-developer#61]
Link to Delivery Plan:

https://www.notion.so/boolean/API-Delivery-Plan-bb027db5a3394aea8c2f80623c4f5282

**Comment by stevenrico** [comment]
Week One is complete.

Week Two and Three are planned. Content is incomplete.

**Comment by dearshrewdwit** [comment]
- Week 2 (prisma orm, morning content)
- Week 3 outline still to complete
