### ISSUE TITLE
Team projects: end of week team feedback survey

### ISSUE THREAD

**Issue by vherus** [boolean-uk/software-developer#93]
- How many commits did you make on average during sprints
- How many commits did the other members of your team make
- Did you do daily standups
- How accurately did you estimate work for sprints
- What were the biggest challenges you faced as a team
- What were the biggest accomplishments you made as a team
- Were your branch names consistent
- Where your commit messages consistent

**Comment by dearshrewdwit** [comment]
@vherus Is this the relevant survey?

https://docs.google.com/forms/d/e/1FAIpQLSfYid228yAfToVeK-l-CVwA8LjaMz88wW3xK1qDziPhZZRhxA/viewform

**Comment by vherus** [comment]
That's right. I'll remind group 2 again to fill this in today
