### ISSUE TITLE
Create Dev Team Simulation module

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#95]
Delivery Plan outline
> https://www.notion.so/boolean/Module-5-Team-Development-Simulation-73c2a738c9444e3aa0514f2166e9d354

**Comment by vherus** [comment]
Interesting feedback from @Auenc on the API module that may fit into this simulation well:

> Thinking about the introduction to prisma - I'm not sure how possible this is, might need a little bit of a spike to try it out, but perhaps a nice way of introducing fetching data/queries etc using prisma could be to have an exercise that is a basic CRUD API writing using the pg library (but having the schema and tables built via prisma) and have the students refactor each endpoint using the prisma client? I think it could be a nice way of introducing the benefits of using an ORM, especially showing off how much less lines of code it is to do the DB interactions. I think a potential downside might be that it would involve refactoring work, although this could be extra practice in working within existing code
