### ISSUE TITLE
Add Full-Stack app to Backend module

### ISSUE THREAD

**Issue by mikemherron** [boolean-uk/software-developer#99]
In the current backend module students never get the opportunity to build an entire full stack app, unless they get to the extensions on the cinema booking API. With C4, I've been using Miro extensivley to show how the APIs we are building could be used with a React app, to try and give them the right 
mental model, but it needs to be repeated often. 

Providing them with the opportunity earlier in the module to build an API and hook up an actual front-end themselves (either developed from scratch or using a pre made starting point) might help their understanding.

**Comment by Auenc** [comment]
> Something they've already done previously (like a todo list, softplay, cohort manager)

This is a great idea. We could take one of the previous react apps they made that use json-server as their backend. Then replicate the functionality with their own backend?

**Comment by vherus** [comment]
I'll take a look at those json-server react exercises to see which one would fit best. @mikemherron if we place this exercise after express but before the database-design stuff, will they have been doing SQL with pg or should it just use a hardcoded dataset?

**Comment by mikemherron** [comment]
Yes, the way I did it this week / last week they did a CRUD API with plain SQL, so that timing sounds perfect.

**Comment by vherus** [comment]
1: https://www.notion.so/boolean/cf71e104602440a2b22ea756e7c7e6e3?v=1e925ad0c4874290811a1f1a8bee0783&p=0d717328f3eb415c9ac0732774de554c

2: https://github.com/boolean-uk/auth-client
